### ISSUE TITLE
Brno requirements

### ISSUE THREAD

**Issue by theyoyojo** [underground-software/singularity#169]
Brno group can setup, configure, maintain, and understand the infrastructure

Students send patches with git send-email for assignments

Students can confirm that their submissions are received

Make info except for names & content available on public dashboard

Instructors can easily check which students have submitted any assignment

No peer review process

Students cannot access pop

**Comment by charliemirabile** [comment]
I feel like changing to public shared dashboard is too much of a change for a separate instance. While we could code it up, I would not be interested in maintaining it as a second branch going forward.

Not hard to have instructors run a script to run on the host machine with output that tells which students did or did not do a particular assignment and which submission ID is whose, but it would be easier to just keep a per student dashboard for checking if their work was received on the web.

**Comment by theyoyojo** [comment]
Fall 2024 MUNI course decided not to go with singularity
